config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'home#show'

  resources :foobars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foobars_controller.rb
class FoobarsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foobars_helper.rb
module FoobarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foobars/index.html.erb
<h1>This is Foobars</h1>

<%= react_component "HelloWorld", greeting: "FOOBARS" %>

app/views/home/show.html.erb
<p>Do a fart?</p>

<%= react_component("HelloWorld", greeting: 'fuckass') %>

<p>
<%= link_to 'foobars', foobars_path , id: :fuckass %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactRetreat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <p>A header. Or something.</p>
      <%= react_component "HelloWorld", greeting: Time.now.to_i %>
    </div>
    <%= yield %>
  </body>
</html>